name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up C++ Build Environment
      run: sudo apt-get install -y build-essential

    - name: Build Project
      run: |
        g++ -o main main.cpp
        ./main
